### ISSUE TITLE
Data.Foldable1

### ISSUE THREAD

**Issue by ysangkok** [flipstone/flipstone-prelude#10]
The module [Data.Foldable1](https://hackage.haskell.org/package/base-4.19.1.0/docs/Data-Foldable1.html), available in base from GHC 9.6 and up, is also implemented in the Hackage package [foldable1-classes-compat](https://hackage.haskell.org/package/foldable1-classes-compat). We could conditionally depend on this package and thus provide safe versions of foldl1.

We have a comment that notes how the old version of foldl1 is unsafe:

> `foldl` is considered dangerous, also omitted are the functions which will throw, `foldr1` and `foldl1`

Given that the prelude already exports NonEmpty and sconcat, these functions would go nicely with those. Note how `fold1` is similar to sconcat.

There is also a safe `head`.

It also has safe versions of `maximumBy` and `minimumBy`, which we now export unsafe versions of.

**Comment by ysangkok** [comment]
@jlavelle @telser What about I just swap out maximumBy and minimumBy? Would that break a lot of your stuff?

**Comment by ysangkok** [comment]
Just read through https://github.com/haskell/core-libraries-committee/issues/9 , which provides some motivation for not re-exporting all of this. So that's why I propose just replacing the partial ones we have now.

**Comment by telser** [comment]
An interesting option here is to simply not support things before 9.6. I'm not sure how wide we want to support or spread this package. If we are going to keep it more internally targeted then maybe it's fine to drop 9.4 and earlier?

**Comment by jlavelle** [comment]
I would love to have the `Foldable1` functions exported

**Comment by ysangkok** [comment]
@telser I don't see why we wouldn't use the compat package? Given that we can drop it within half a year, it doesn't have to work for a long time. It's made by Ryan G. Scott, who is a pretty reputable Haskeller.

I consider the danger of keeping maximumBy/minimumBy as larger than whatever problems we could have using the compat package.

Potential dangers using the compat package:
* Doesn't have the same performance characteristics as the base version, resulting in confusing changes once we upgrade to GHC 9.6.

Potential dangers keeping the partial functions around:
* We encode things as lists in our APIs while they should be NonEmpty's, making more work for us when we eventually need to fix those partial calls and change API types all over.

Comparing these scenarios, the latter seems much worse, would you not agree?
